sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
notifications:
  email: false
  slack: 8labsolutions:xbZmb6AJptYE00snoApiI1F1
cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest
  - npm install -g ganache-cli truffle
install:
  - npm install
jobs:
  include:
    - stage: deploy
      script:
        - npm run lint
        - npm run build
        - ganache-cli -p 9545 > /dev/null &
        - sleep 5
        - truffle migrate --reset
      deploy:
        provider: surge
        skip_cleanup: true
        domain: soldino.surge.sh
        project: ./build/
        on:
          all_branches: true
